/**
 * Expo config plugin: make debug APKs embed their JS bundle AND run without the
 * Metro dev server - a true standalone build off the debug signing key.
 *
 * A normal RN debug build loads JS from Metro, so the app dies the moment you
 * unplug from the PC - useless for an untethered in-car test or for handing a
 * build to a tester. Two things make a debug variant self-contained:
 *
 *   1. BUNDLE THE JS. React Native's gradle plugin only bundles JS for variants
 *      listed in `react { debuggableVariants }` (default [debug], so debug is NOT
 *      bundled). Setting it to [] makes debug bundle its own (--dev false) JS.
 *
 *   2. DISABLE DEV SUPPORT. Even with JS bundled, a debug variant still has
 *      ReactBuildConfig.DEBUG=true, so Expo's ExpoReactHostFactory defaults
 *      `useDevSupport = ReactBuildConfig.DEBUG` = true. The New-Arch
 *      DevSupportManager then tries to reach ws://localhost:8081 and shows the
 *      "connect to a development server" screen with no PC nearby. We pass an
 *      explicit `useDevSupport = false` into getDefaultReactHost() so the host
 *      loads the embedded bundle and never opens the packager connection.
 *
 * Both edits target gitignored files regenerated by prebuild (android/app/
 * build.gradle and MainApplication.kt), so they live here as a plugin and are
 * reapplied automatically. Gated by env so day-to-day Metro dev is unaffected:
 *   HEARTHSHELF_STANDALONE_DEBUG=1 npx expo prebuild --platform android
 */
const { withAppBuildGradle, withMainApplication } = require('expo/config-plugins')

function withBundledJs(config) {
  return withAppBuildGradle(config, (cfg) => {
    let src = cfg.modResults.contents

    // Idempotency: only bail if a REAL (uncommented) assignment is already
    // present. The RN template ships a commented `// debuggableVariants = []`
    // example line, so a naive substring check matches that and does nothing -
    // leaving debug unbundled and the APK unable to find its JS at runtime.
    // Require a line where the assignment is the first non-space token.
    if (/^\s*debuggableVariants\s*=/m.test(src)) return cfg

    // Inject a real assignment as the first statement inside the react { } block.
    // (Editing the commented example is brittle; an explicit insert is clearer
    // and survives template wording changes.)
    if (/react\s*\{/.test(src)) {
      src = src.replace(/react\s*\{/, 'react {\n    debuggableVariants = []')
    } else {
      // No react block (unexpected for an RN app); append a minimal one.
      src += '\nreact {\n    debuggableVariants = []\n}\n'
    }

    cfg.modResults.contents = src
    return cfg
  })
}

function withDevSupportDisabled(config) {
  return withMainApplication(config, (cfg) => {
    let src = cfg.modResults.contents

    // Idempotent: already patched.
    if (/useDevSupport\s*=\s*false/.test(src)) return cfg

    // The generated call is:
    //   ExpoReactHostFactory.getDefaultReactHost(
    //     context = applicationContext,
    //     packageList = ...
    // Insert `useDevSupport = false,` right after the `context =` argument so the
    // host loads the embedded bundle instead of defaulting to ReactBuildConfig.DEBUG.
    if (/getDefaultReactHost\s*\(/.test(src) && /context\s*=\s*applicationContext\s*,/.test(src)) {
      src = src.replace(
        /(context\s*=\s*applicationContext\s*,)/,
        '$1\n      useDevSupport = false,'
      )
    } else {
      throw new Error(
        '[standalone-js] Could not find the getDefaultReactHost(context = applicationContext, ...) ' +
          'call in MainApplication to disable dev support. The Expo template may have changed.'
      )
    }

    cfg.modResults.contents = src
    return cfg
  })
}

module.exports = function withStandaloneJs(config) {
  if (process.env.HEARTHSHELF_STANDALONE_DEBUG !== '1') return config
  config = withBundledJs(config)
  config = withDevSupportDisabled(config)
  return config
}
