/**
 * Lint config - deliberately NARROW.
 *
 * This exists for one reason: rules-of-hooks. In a single session three screens
 * (app/item/[id].tsx, app/series/[id].tsx, app/player.tsx) each declared a hook
 * next to its first use, BELOW an early return - so the two render paths called
 * different numbers of hooks. React throws "Rendered more hooks than during the
 * previous render" and unmounts the screen, which without an error boundary is a
 * blank white page and, in Sentry, nothing at all. All three were mechanically
 * detectable; they spread only because the pattern was copy-pasted between
 * screens. This rule catches them at author time for free.
 *
 * Everything else is intentionally left OFF (not merely un-erroring). The repo
 * has ~200 files written without a linter, so turning on the full Expo preset
 * would bury the one rule that matters under hundreds of pre-existing style
 * findings and train everyone to ignore the output. Prettier already owns
 * formatting (`npm run format`), and tsc owns type correctness.
 *
 * Add more rules deliberately, one at a time, each with the existing code
 * cleaned up to pass - not in a bulk preset switch-on.
 */
const { defineConfig } = require('eslint/config')
const reactHooks = require('eslint-plugin-react-hooks')
const tsParser = require('@typescript-eslint/parser')

module.exports = defineConfig([
  {
    ignores: [
      'node_modules/**',
      'android/**', // generated by expo prebuild
      'ios/**', // generated by expo prebuild
      'packages/core/**', // git submodule, linted in its own repo
      '.expo/**',
      'dist/**',
    ],
  },
  {
    // The codebase carries `eslint-disable react-hooks/exhaustive-deps` comments
    // from before this config existed. That rule is off here, so ESLint would
    // report every one as an unused directive - 15 warnings that say nothing and
    // would drown the errors that matter. The comments are also correct
    // documentation of intent, and stay valid if exhaustive-deps is turned on
    // later, so they are kept rather than stripped.
    linterOptions: { reportUnusedDisableDirectives: 'off' },
  },
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    // TS parser for everything: without it ESLint's default parser chokes on
    // type annotations and reports "Parsing error" for ~200 files, which hides
    // the one rule this config exists to run. No `project` / type-aware linting -
    // rules-of-hooks is purely syntactic, and type-aware mode would make lint as
    // slow as a full tsc run for no benefit here.
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      // The whole point of this config. Error, never warn: a violation is a
      // screen that unmounts itself at runtime, not a style preference.
      'react-hooks/rules-of-hooks': 'error',
      // Missing deps are a real bug class too, but the existing code has many
      // deliberate omissions (mount-once effects). Off until they can be audited
      // one at a time rather than silenced in bulk.
      'react-hooks/exhaustive-deps': 'off',
    },
  },
])
