/**
 * Expo config plugin: wire an Android RELEASE signing config into the generated
 * android/app/build.gradle at prebuild time.
 *
 * android/ is gitignored and regenerated by `expo prebuild`, so a hand edit to
 * build.gradle is lost on every prebuild. As a config plugin this is reapplied
 * automatically - the same durability pattern as plugins/standalone-js.
 *
 * NOTHING secret lives here or in the repo. The keystore itself and its
 * passwords come from environment variables, so the exact same setup works on:
 *   - CI: the keystore is a base64 GitHub Actions secret, decoded to a file on
 *     the runner; passwords are secrets. (See build-android-release.yml.)
 *   - Locally: point the vars at your own upload.jks for a test release build.
 *
 * Gated by HEARTHSHELF_RELEASE_SIGNING=1 so ordinary debug prebuilds/builds are
 * completely unaffected (the release signingConfig is only injected when asked).
 *
 * Required env when enabled:
 *   HEARTHSHELF_RELEASE_SIGNING=1
 *   HEARTHSHELF_RELEASE_KEYSTORE_PATH   absolute path to the .jks on this machine
 *   HEARTHSHELF_RELEASE_KEYSTORE_PASSWORD
 *   HEARTHSHELF_RELEASE_KEY_ALIAS
 *   HEARTHSHELF_RELEASE_KEY_PASSWORD
 *
 * With Google Play App Signing (recommended), this upload key only signs the
 * .aab you upload; Google re-signs with the real app-signing key. So the
 * SHA-256 to register for native Google sign-in is the Play Console
 * "app signing key certificate" SHA, NOT this upload key's SHA. See RELEASE.md.
 */
const { withAppBuildGradle } = require('expo/config-plugins')

const REQUIRED = [
  'HEARTHSHELF_RELEASE_KEYSTORE_PATH',
  'HEARTHSHELF_RELEASE_KEYSTORE_PASSWORD',
  'HEARTHSHELF_RELEASE_KEY_ALIAS',
  'HEARTHSHELF_RELEASE_KEY_PASSWORD',
]

module.exports = function withHearthshelfSigning(config) {
  if (process.env.HEARTHSHELF_RELEASE_SIGNING !== '1') return config

  const missing = REQUIRED.filter((k) => !process.env[k])
  if (missing.length) {
    // Fail loud at prebuild rather than silently producing a debug-signed (or
    // unsigned) release the store will reject. A half-configured signing setup
    // is worse than an obvious error.
    throw new Error(
      `[hearthshelf-signing] HEARTHSHELF_RELEASE_SIGNING=1 but missing: ${missing.join(', ')}`,
    )
  }

  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        `[hearthshelf-signing] expected a Groovy build.gradle, got ${cfg.modResults.language}`,
      )
    }

    let src = cfg.modResults.contents

    // Idempotency: if we've already injected our release config, do nothing.
    if (src.includes('// hearthshelf-signing:release')) return cfg

    // The signing values are read from Gradle project properties at build time
    // (passed via -P or ~/.gradle/gradle.properties or ORG_GRADLE_PROJECT_* env
    // vars) so no secret is ever written into build.gradle itself. The config
    // plugin only injects the *wiring*; the values stay in the environment.
    const signingConfigBlock = [
      '            // hearthshelf-signing:release',
      '            release {',
      "                storeFile file(providers.gradleProperty('HEARTHSHELF_RELEASE_KEYSTORE_PATH').get())",
      "                storePassword providers.gradleProperty('HEARTHSHELF_RELEASE_KEYSTORE_PASSWORD').get()",
      "                keyAlias providers.gradleProperty('HEARTHSHELF_RELEASE_KEY_ALIAS').get()",
      "                keyPassword providers.gradleProperty('HEARTHSHELF_RELEASE_KEY_PASSWORD').get()",
      '            }',
    ].join('\n')

    // Order matters: repoint the release buildType FIRST, then inject the new
    // signingConfig. Step 1 adds a `release { ... }` block inside
    // signingConfigs; if we did that before step 2, the release-buildType regex
    // below would match our freshly injected block instead. Doing step 2 first
    // means the only `release {` in the source is the buildType.

    // 1. Point the `release` buildType at a (not-yet-created) release
    //    signingConfig. The RN template ships TWO `signingConfig
    //    signingConfigs.debug` lines: one in the debug buildType (must stay
    //    debug - the debug SHA is what Clerk/assetlinks trust) and one in the
    //    release buildType (defaults to the debug key so assembleRelease works
    //    out of the box). Repoint ONLY the release one by anchoring on the
    //    `release {` buildType block.
    const releaseBlock = /(release\s*\{[\s\S]*?)signingConfig\s+signingConfigs\.debug/
    if (!releaseBlock.test(src)) {
      throw new Error(
        '[hearthshelf-signing] could not find the release buildType `signingConfig signingConfigs.debug` to repoint',
      )
    }
    src = src.replace(releaseBlock, '$1signingConfig signingConfigs.release')

    // 2. Now add the `release` entry inside `signingConfigs { ... }`. The RN
    //    template always ships a `signingConfigs { debug { ... } }` block;
    //    insert right after the opening brace.
    if (!/signingConfigs\s*\{/.test(src)) {
      throw new Error('[hearthshelf-signing] no signingConfigs block found in build.gradle')
    }
    src = src.replace(/signingConfigs\s*\{/, `signingConfigs {\n${signingConfigBlock}`)

    cfg.modResults.contents = src
    return cfg
  })
}
